# The general settings
[general]

# Environment variables for things run in Alacritty
[env]

# Window styling options
[window]

# Padding to make things a bit more comfy
padding = { x = 2, y = 2 }

# Turning off the window frame
decorations = "None"

# Scrolling settings
[scrolling]

# Cursor settings
[cursor]
style = { shape = "Block", blinking = "On" }

# Font settings
[font]
normal = { family = "Pragmata Pro Mono", style = "Regular" }
bold = { style = "Bold"}
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
builtin_box_drawing = false

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_night.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
